// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android; // Use Android config for Linux development
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8epfR3MAWSYMaqk9VXXYVjSQMKG9fEbA',
    appId: '1:949338416443:web:e958d1632234a75590431e',
    messagingSenderId: '949338416443',
    projectId: 'roomease-2025',
    authDomain: 'roomease-2025.firebaseapp.com',
    storageBucket: 'roomease-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNM-gh1Dy8YL8GzcgEiy6ZKvNnkvCkyM',
    appId: '1:949338416443:android:eb70117de69b8e8690431e',
    messagingSenderId: '949338416443',
    projectId: 'roomease-2025',
    storageBucket: 'roomease-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVd5PXLYdCAoHR0H18PT8lj6yCx3WsnV0',
    appId: '1:949338416443:ios:630ac68c75f3611990431e',
    messagingSenderId: '949338416443',
    projectId: 'roomease-2025',
    storageBucket: 'roomease-2025.firebasestorage.app',
    androidClientId: '949338416443-bljrf0undk633j4j53nlvj824qh3gjmv.apps.googleusercontent.com',
    iosClientId: '949338416443-lv86qbku6obcvud51qnqprpct8hjsvm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVd5PXLYdCAoHR0H18PT8lj6yCx3WsnV0',
    appId: '1:949338416443:ios:630ac68c75f3611990431e',
    messagingSenderId: '949338416443',
    projectId: 'roomease-2025',
    storageBucket: 'roomease-2025.firebasestorage.app',
    androidClientId: '949338416443-bljrf0undk633j4j53nlvj824qh3gjmv.apps.googleusercontent.com',
    iosClientId: '949338416443-lv86qbku6obcvud51qnqprpct8hjsvm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8epfR3MAWSYMaqk9VXXYVjSQMKG9fEbA',
    appId: '1:949338416443:web:b239eb7540d3137490431e',
    messagingSenderId: '949338416443',
    projectId: 'roomease-2025',
    authDomain: 'roomease-2025.firebaseapp.com',
    storageBucket: 'roomease-2025.firebasestorage.app',
  );

}